name: Build and deploy APK

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Install jq (for JSON validation)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_BASE64: ${{ secrets.GOOGLE_SERVICES_BASE64 }}
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
        run: |
          # Try Base64 encoded secret first (recommended approach)
          if [ ! -z "$GOOGLE_SERVICES_BASE64" ]; then
            echo "$GOOGLE_SERVICES_BASE64" | base64 --decode > app/google-services.json
            echo "Using base64 encoded Google Services file"
          # Fall back to direct JSON secret if available
          elif [ ! -z "$GOOGLE_SERVICES" ]; then
            echo "$GOOGLE_SERVICES" > app/google-services.json
            echo "Using direct JSON Google Services file"
          else
            # Create a minimal placeholder if no secret available (build will likely fail without proper config)
            echo '{"project_info":{"project_id":"dummy-project-id"}}' > app/google-services.json
            echo "WARNING: Using minimal placeholder google-services.json. Build will likely fail!"
          fi

      - name: Validate google-services.json
        run: |
          echo "Validating google-services.json file..."
          if ! jq empty app/google-services.json; then
            echo "ERROR: Invalid google-services.json file - not valid JSON!"
            exit 1
          fi
          
          # Check for basic required structure
          if ! jq -e '.project_info' app/google-services.json > /dev/null; then
            echo "ERROR: Invalid google-services.json file - missing project_info!"
            exit 1
          fi
          
          echo "google-services.json file is valid JSON with basic structure"
          # Print sanitized structure (no sensitive values)
          jq 'keys' app/google-services.json
          
          # Debug: show file size
          ls -la app/google-services.json

      - name: Create local.properties with Gemini API key
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY || 'dummy-api-key' }}
        run: |
          echo "gemini.api.key=$GEMINI_API_KEY" > local.properties

      - name: Build Release APK
        run: ./gradlew clean assembleRelease --stacktrace --warning-mode all

      - name: Verify APK was built
        run: |
          if [ ! -f app/build/outputs/apk/release/app-release.apk ] && [ ! -f app/build/outputs/apk/release/app-release-unsigned.apk ]; then
            echo "APK file was not created!"
            exit 1
          fi

      - name: Rename APK file
        run: |
          cd app/build/outputs/apk/release
          if [ -f app-release.apk ]; then
            mv app-release.apk Tasky.apk
          elif [ -f app-release-unsigned.apk ]; then
            mv app-release-unsigned.apk Tasky.apk
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: tasky-apk
          path: 'app/build/outputs/apk/release/Tasky.apk'