name: Coverage Report

on:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $GOOGLE_SERVICES > app/google-services.json

      - name: Run Tests
        run: ./gradlew clean createDebugUnitTestCoverageReport

      - name: Upload Unit Tests Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: Tasky-Coverage-Report
          path: 'app/build/reports/coverage/test/debug/'