name: Documentation

on:
  push:
    branches:
      - main

jobs:
  documentation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
        run: |
          echo "$GOOGLE_SERVICES" | base64 --decode > app/google-services.json
          cat app/google-services.json | jq '.'
          

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "gemini.api.key=${{ secrets.GEMINI_API_KEY }}" >> local.properties
          ls -la
          cat local.properties
          pwd

      - name: Generate documentation
        run: ./gradlew clean app:dokkaHtml --warning-mode all --stacktrace

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: Tasky-Documentation
          path: 'app/build/dokka/html'