name: Documentation

on:
  push:
    branches:
      - main

jobs:
  documentation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_BASE64: ${{ secrets.GOOGLE_SERVICES_BASE64 }}
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
        run: |
          # Try Base64 encoded secret first (recommended approach)
          if [ ! -z "$GOOGLE_SERVICES_BASE64" ]; then
            echo "$GOOGLE_SERVICES_BASE64" | base64 --decode > app/google-services.json
            echo "Using base64 encoded Google Services file"
          # Fall back to direct JSON secret if available
          elif [ ! -z "$GOOGLE_SERVICES" ]; then
            echo "$GOOGLE_SERVICES" > app/google-services.json
            echo "Using direct JSON Google Services file"
          else
            # Create a minimal placeholder if no secret available
            echo '{"project_info":{"project_id":"dummy-project-id"}}' > app/google-services.json
            echo "WARNING: Using minimal placeholder google-services.json."
          fi
          
          # Validate the JSON file
          if ! jq empty app/google-services.json; then
            echo "ERROR: Invalid google-services.json file - not valid JSON!"
            exit 1
          fi

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "gemini.api.key=${{ secrets.GEMINI_API_KEY }}" >> local.properties
          ls -la
          cat local.properties
          pwd

      - name: Generate documentation
        run: ./gradlew clean app:dokkaHtml --warning-mode all --stacktrace

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: Tasky-Documentation
          path: 'app/build/dokka/html'